######################################################################
# Automatically generated by qmake (3.1) Sun Jun 19 01:32:07 2022
######################################################################

QT += testlib concurrent widgets
TEMPLATE = app
TARGET = test
INCLUDEPATH += ../src
CONFIG += c++11
CONFIG += warn_on

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input


HEADERS += \
    ../src/asynctextwriter.h \

SOURCES += asynctextwritertest.cpp \
    ../src/asynctextwriter.cpp
