name: ghostwriter
version: 1.4.2
summary: ghostwriter is a cross-platform, aesthetic, distraction-free Markdown editor
description: |
  ghostwriter is a Windows and Linux text editor for Markdown,
  which is a plain text markup format created by John Gruber.
  For more information about Markdown, please visit John Gruber’s
  website at http://www.daringfireball.net. ghostwriter provides
  a relaxing, distraction-free writing environment, whether your
  masterpiece be that next blog post, your school paper, or your
  NaNoWriMo novel.

confinement: strict # devmode
grade: devel        # must be 'stable' to release into candidate/stable channels

apps:
  ghostwriter:
    command: desktop-launch $SNAP/usr/local/bin/ghostwriter
    plugs: [home, x11, opengl, unity7] # network?

parts:
  ghostwriter:
    plugin: qmake
    qt-version: qt5
    source: https://github.com/wereturtle/ghostwriter.git
    project-files:
      - ghostwriter.pro
    stage-packages:
      - build-essential
      - libhunspell-dev
      - pkg-config
      - qtbase5-dev
      - qtmultimedia5-dev
      - libqt5concurrent5
      - libqt5printsupport5
      - libqt5svg5
      - qt5-default
      - libqt5svg5-dev
      - libqt5webkit5-dev
    after: [desktop-qt5]
    snap:
      # delete files & folders by prefixing them with a -
      - -usr/share/doc
