.\" Manpage for ghostwriter.
.TH man 1 "16 September 2017" "1.6.0" "ghostwriter man page"
.SH NAME
ghostwriter \- distraction\-free text editor for Markdown
.SH SYNOPSIS
ghostwriter [file]
.SH DESCRIPTION
Qt text editing application for Markdown that provides an aesthetic,
distraction\-free writing environment.
Create your own custom themes, write in fullscreen mode, or use focus mode
to concentrate on just one or more lines.
A live HTML preview allows you to view the final formatting as you type.
HTML preview and export options are provided by the built-in Markdown processor,
Sundown;  but you may add more by installing Pandoc, MultiMarkdown, Discount,
cmark, or cmark-gfm processors.  The application will automatically detect their
installation if their locations are in the system's PATH environment variable.
.SH AUTHOR
wereturtle
.SH REPORTING BUGS
See http://github.com/wereturtle/ghostwriter/
.SH COPYRIGHT
Licensed under the GNU GPL3+.
.SH SEE ALSO
Why aren't you writing?
