.\" Manpage for ghostwriter.
.TH man 1 "19 August 2015" "1.0" "ghostwriter man page"
.SH NAME
ghostwriter \- distraction\-free text editor for Markdown
.SH SYNOPSIS
ghostwriter [file\&...]
.SH DESCRIPTION
Qt text editing application for Markdown that provides an aesthetic,
distraction\-free writing environment.
Create your own custom themes, write in full screen, or use focus mode
to concentrate on just one or more lines.
A live HTML preview allows you to view the final formatting as you type.
.SH AUTHOR
wereturtle
.SH REPORTING BUGS
See http://github.com/wereturtle/ghostwriter/
.SH COPYRIGHT
Licensed under the GNU GPL3+.
.SH SEE ALSO
Why aren't you writing?